name: Deploy frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -vzr --delete
          path: dist/
          remote_path: /var/www/html/
          remote_host: 217.12.38.239
          remote_user: root
          remote_key: ${{ secrets.SSH_PRIVATE_KEY  }}
